"""Oracle agent — value model (numpy inference).

A small MLP trained on top-ladder replays (scripts/oracle_train.py) maps the
shared feature vector to (P(win), final score share). Weights ship inside
the bundle as base64 float32 blobs in value_weights.py. Until trained
weights exist, a transparent heuristic fallback keeps the agent playable:
the forecast production/score shares at the deepest probe.

The planner maximizes a single scalar: P(win) + SHARE_W * share. P(win) is
the objective that matters (ratings ignore margin); the share term gives a
gradient where the win head saturates (early game, crushed/crushing).
"""

import math
import os

import numpy as np

from .features import FEATURE_NAMES

SHARE_W = float(os.environ.get("ORACLE_SHARE_W", "0.25"))

_I_SHARE_SCORE_LAST = FEATURE_NAMES.index("share_score_t32")
_I_SHARE_PROD_LAST = FEATURE_NAMES.index("share_prod_t32")


class ValueNet:
    def __init__(self):
        self.loaded = False
        try:
            from . import value_weights as VW
            self.mu = VW.MU
            self.sigma = VW.SIGMA
            self.layers = VW.LAYERS          # [(W, b), ...] hidden stack
            self.head_win = VW.HEAD_WIN      # (W, b)
            self.head_share = VW.HEAD_SHARE  # (W, b)
            self.loaded = True
        except Exception:
            pass

    def batch(self, feats_list):
        """list of feature vectors -> np.array of scalar plan scores."""
        if not feats_list:
            return np.zeros(0, dtype=np.float32)
        X = np.asarray(feats_list, dtype=np.float32)
        if not self.loaded:
            share = X[:, _I_SHARE_SCORE_LAST]
            prod = X[:, _I_SHARE_PROD_LAST]
            return 0.45 * share + 0.55 * prod
        Z = (X - self.mu) / self.sigma
        for W, b in self.layers:
            Z = Z @ W + b
            np.maximum(Z, 0.0, out=Z)
        win_logit = Z @ self.head_win[0] + self.head_win[1]
        share = Z @ self.head_share[0] + self.head_share[1]
        p_win = 1.0 / (1.0 + np.exp(-win_logit))
        return p_win + SHARE_W * np.clip(share, 0.0, 1.0)


def encode_weights_py(arrays: dict, head_names=("WIN", "SHARE")) -> str:
    """Render trained arrays into a *_weights.py module source.

    arrays: {"mu", "sigma", "layers": [(W, b), ...],
             "head_<lower(name)>": (W, b) for each head name}
    """
    import base64
    lines = ["# Generated by the oracle training scripts — do not edit.",
             "import base64", "import numpy as np", ""]

    def enc(name, a):
        a = np.ascontiguousarray(a, dtype=np.float32)
        blob = base64.b64encode(a.tobytes()).decode()
        lines.append(
            f"{name} = np.frombuffer(base64.b64decode("
            f"'{blob}'), dtype=np.float32).reshape({a.shape}).copy()")

    enc("MU", arrays["mu"])
    enc("SIGMA", arrays["sigma"])
    for k, (W, b) in enumerate(arrays["layers"]):
        enc(f"_W{k}", W)
        enc(f"_b{k}", b)
    lines.append("LAYERS = [" + ", ".join(
        f"(_W{k}, _b{k})" for k in range(len(arrays["layers"]))) + "]")
    for nm in head_names:
        W, b = arrays[f"head_{nm.lower()}"]
        enc(f"_W_{nm}", W)
        enc(f"_B_{nm}", b)
        lines.append(f"HEAD_{nm} = (_W_{nm}, "
                     f"float(_B_{nm}[0]) if _B_{nm}.ndim else _B_{nm})")
    lines.append("")
    return "\n".join(lines)
