"""Cluster-conditional opening overlay.

At step 0, classify the board into one of 4 clusters via the KMeans
model fit on top-10 win replays (`audit/2026-05-14-opening-overlay-
model.json`). For steps 0-30, the overlay proposes launches matching
the cluster's empirical opening template:

| cluster | first launch | launches in 30 | target dist | target prod | launches / turn |
|---|---|---|---|---|---|
| 0 (sparse-static-rich)        | t=5  | 4   | 44 | 3.5 | 0.73 |
| 1 (wide-mixed; blitz regime) | t=4  | 7.5 | 45 | 3.0 | 1.03 |
| 2 (close-quarters)           | t=1.5| 5   | 44 | 2.6 | 0.59 |
| 3 (close-quarters-orbital)   | t=4  | 6   | 37 | 3.3 | 0.69 |

After step 30 the overlay returns `None`, ceding control to the
caller (v7 search). The overlay is hand-off-clean: any state it
caches lives on the agent-side closure, never inside lib state.

The model JSON is embedded as a Python dict at module-load time so
the agent can be bundled by `scripts/bundle_agent.py` without an
external file dependency.
"""

from __future__ import annotations

import math
from dataclasses import dataclass


# ---------------------------------------------------------------------------
# Baked KMeans model. Source: audit/2026-05-14-opening-overlay-model.json
# (regenerated by `python -m scripts.eda.fit_opening_overlay` or the inline
# fit in audit/eda-2026-05-14/mine_wins_vs_losses.py). Updating this dict
# requires rerunning the fit + a `git diff` review.
# ---------------------------------------------------------------------------
_MODEL = {
    "features": [
        "n_planets", "orbital_frac", "mean_prod", "std_prod",
        "sun_shadow_frac", "home_pair_min_dist", "home_dist_sun",
        "prod_centroid_dist_sun", "perp_bisector_median_dist", "angular_velocity",
    ],
    "scaler_mean": [
        28.566666666666666, 0.36888611527077506, 2.726041666666667,
        1.5708876197196566, 0.20571064908330636, 86.45499987840708,
        45.05537603920386, 0.6595489770175466, 22.74115316680164,
        0.027872080253797795,
    ],
    "scaler_std": [
        3.4006535571061885, 0.07992226751014008, 0.39037681039907956,
        0.20148089569100087, 0.0512283937195185, 21.026322135884247,
        16.030226337167186, 1.7322014366081008, 12.077033898541906,
        0.025149725660019693,
    ],
    "centroids": [
        [-1.3093262378024758, -1.1740137935725075, 1.272395268519005, -0.394988226906149,
         -1.4575611391005775, 1.0114203443538502, 0.9286672859820537, 0.026366810608953116,
         0.5879795033415375, -0.018824989824107],
        [0.5448122379700928, 0.25127817116091655, -0.030842502385129143, 0.2840712641381928,
         0.5167068075395823, 0.7973933772132594, 0.6336942814829506, 0.4621432054527775,
         0.4385129586247632, 0.30049928188353415],
        [-0.7641176470588235, -0.6451812199036499, -0.09898643525559488, -0.18745195019687107,
         -0.30326697879859105, -0.4197898310550168, 0.24149568773862697, -0.24070000076671815,
         -0.8590920660378024, -0.81115540671376],
        [0.3393421052631578, 0.5527083866745515, -0.36801822989697765, -0.060898961537345846,
         0.13144078017434014, -1.025911376378817, -1.2152830488676472, -0.3989822268437373,
         -0.1788776316002948, 0.16690942196717358],
    ],
    "templates": {
        "0": {"first_launch_med": 5.0, "launches_30_med": 4.0, "target_dist_med": 44.07, "target_prod_med": 3.50},
        "1": {"first_launch_med": 4.0, "launches_30_med": 7.5, "target_dist_med": 44.78, "target_prod_med": 3.00},
        "2": {"first_launch_med": 1.5, "launches_30_med": 5.0, "target_dist_med": 43.79, "target_prod_med": 2.62},
        "3": {"first_launch_med": 4.0, "launches_30_med": 6.0, "target_dist_med": 36.74, "target_prod_med": 3.33},
    },
}

# Window during which the overlay overrides. After OVERLAY_HORIZON we
# hand back to v7. Pinned to the corpus boundary (template medians were
# computed over the first 30 turns).
OVERLAY_HORIZON = 30


@dataclass(frozen=True)
class Template:
    first_launch: int
    launches_30: float
    target_dist: float
    target_prod: float


def _board_fingerprint(planets, omega: float) -> dict:
    """Subset of `scripts/eda/board_features.board_features` that runs
    from the live obs without re-reading a replay file. Returns the 10
    features in `_MODEL['features']` order.

    `path_clears_sun` and `is_orbiting` are inlined to keep the overlay
    self-contained for bundling.
    """
    n = len(planets)
    homes = [p for p in planets if p[1] >= 0]
    n_seats = len(homes)
    prods = [p[6] for p in planets]
    mean_prod = sum(prods) / n if n else 0.0
    var_prod = sum((p - mean_prod) ** 2 for p in prods) / (n - 1) if n > 1 else 0.0
    std_prod = math.sqrt(var_prod)
    # Orbital = nonzero ang-vel orbit (per lib.orbit.is_orbiting: planet
    # whose radius coordinate is non-trivial; the bundled simplification
    # is `omega != 0 and idx > 0` — comets always orbit, planets fixed
    # unless flagged. The replay-side extractor uses lib.orbit; here we
    # approximate by counting planets whose initial position differs
    # from CENTER (50, 50) since fixed planets in this comp are
    # axis-aligned). This proxy yielded the same cluster assignments
    # in the smoke test below (cf. unit test).
    # Inlined from lib.orbit.is_orbiting (kept inline so a bundled
    # single-file agent doesn't need lib/orbit at runtime). A planet
    # orbits iff orbital_radius + planet_radius < ROTATION_RADIUS_LIMIT
    # (50.0 in lib.geometry); static planets sit outside that ring.
    # The earlier sentinel-based heuristic counted every non-centre
    # planet as orbital and inflated orbital_frac to 1.00 on every
    # self-play board (vs the training corpus's 0.27-0.44), pushing
    # the runtime feature distribution 7+ sigma from any centroid.
    cx_sun, cy_sun = 50.0, 50.0
    rotation_radius_limit = 50.0
    orb_count = 0
    for p in planets:
        orb_r = math.hypot(p[2] - cx_sun, p[3] - cy_sun)
        if (orb_r + p[4]) < rotation_radius_limit:
            orb_count += 1
    orbital_frac = orb_count / n if n else 0.0
    # Sun-shadow: planet pair blocked by the sun. Linear sun_radius=5.
    SUN_R = 5.0
    blocked, total = 0, 0
    for i in range(n):
        ax, ay = planets[i][2], planets[i][3]
        for j in range(i + 1, n):
            bx, by = planets[j][2], planets[j][3]
            # Closest approach of line a-b to (50, 50)
            dx, dy = bx - ax, by - ay
            L = math.hypot(dx, dy)
            if L < 1e-9:
                total += 1
                continue
            t = ((cx_sun - ax) * dx + (cy_sun - ay) * dy) / (L * L)
            t = max(0.0, min(1.0, t))
            px, py = ax + t * dx, ay + t * dy
            d_min = math.hypot(px - cx_sun, py - cy_sun)
            if d_min < SUN_R:
                blocked += 1
            total += 1
    sun_shadow_frac = blocked / total if total else 0.0
    home_pair_min = None
    if n_seats >= 2:
        ds = []
        for i in range(n_seats):
            for j in range(i + 1, n_seats):
                ds.append(math.hypot(homes[i][2] - homes[j][2], homes[i][3] - homes[j][3]))
        home_pair_min = min(ds)
    home_dist_sun = (
        sum(math.hypot(h[2] - cx_sun, h[3] - cy_sun) for h in homes) / n_seats if n_seats else 0.0
    )
    tot_prod = sum(prods) or 1.0
    pcx = sum(p[2] * p[6] for p in planets) / tot_prod
    pcy = sum(p[3] * p[6] for p in planets) / tot_prod
    prod_centroid_dist_sun = math.hypot(pcx - cx_sun, pcy - cy_sun)
    perp_med = 0.0
    if n_seats == 2:
        x0, y0 = homes[0][2], homes[0][3]
        x1, y1 = homes[1][2], homes[1][3]
        mx, my = (x0 + x1) / 2, (y0 + y1) / 2
        nx, ny = x1 - x0, y1 - y0
        nlen = math.hypot(nx, ny)
        if nlen > 0:
            ds = []
            for p in planets:
                if p[1] >= 0:
                    continue
                ddx, ddy = p[2] - mx, p[3] - my
                ds.append(abs(ddx * nx + ddy * ny) / nlen)
            if ds:
                ds.sort()
                perp_med = ds[len(ds) // 2]
    return {
        "n_planets": float(n),
        "orbital_frac": orbital_frac,
        "mean_prod": mean_prod,
        "std_prod": std_prod,
        "sun_shadow_frac": sun_shadow_frac,
        "home_pair_min_dist": float(home_pair_min or 0.0),
        "home_dist_sun": home_dist_sun,
        "prod_centroid_dist_sun": prod_centroid_dist_sun,
        "perp_bisector_median_dist": perp_med,
        "angular_velocity": float(omega),
    }


# Distance threshold beyond which a board is too far from any training
# centroid to trust the template. Set to the training-set p90 (4.31)
# measured on the 60 top-10 win replays — beyond this the overlay
# returns -1 ("unknown / no overlay") and the agent falls back to pure
# v7. Origin: 2026-05-14 within-cluster heterogeneity diagnostic on
# the v2 sweep losing seeds (seed 100: d_min=6.11, well past p90).
OUTLIER_DISTANCE_THRESHOLD = 4.31


def classify_board(planets, omega: float) -> int:
    """Nearest-centroid classifier on the 10-feature board fingerprint.

    Returns the cluster id (0-3) for in-distribution boards, or -1
    when the board is beyond `OUTLIER_DISTANCE_THRESHOLD` from any
    centroid (caller must fall back to a default policy in this case).
    """
    feats = _board_fingerprint(planets, omega)
    x = [feats[f] for f in _MODEL["features"]]
    sm = _MODEL["scaler_mean"]
    ss = _MODEL["scaler_std"]
    xz = [(x[i] - sm[i]) / ss[i] for i in range(len(x))]
    best, best_d2 = 0, float("inf")
    for c_id, c in enumerate(_MODEL["centroids"]):
        d2 = sum((xz[i] - c[i]) ** 2 for i in range(len(c)))
        if d2 < best_d2:
            best_d2 = d2
            best = c_id
    if best_d2 > OUTLIER_DISTANCE_THRESHOLD * OUTLIER_DISTANCE_THRESHOLD:
        return -1
    return best


def template_for(cluster_id: int) -> Template:
    t = _MODEL["templates"][str(cluster_id)]
    return Template(
        first_launch=int(t["first_launch_med"]),
        launches_30=float(t["launches_30_med"]),
        target_dist=float(t["target_dist_med"]),
        target_prod=float(t["target_prod_med"]),
    )


def propose_opening_actions(
    obs,
    my_seat: int,
    cluster_id: int,
    launches_so_far: int,
) -> list[list]:
    """Emit env-format actions matching `template_for(cluster_id)`.

    Returns `[[src_id, aim_angle, ships]]` if we should launch this
    step, else `[]`. Caller is responsible for tracking
    `launches_so_far` across steps.
    """
    planets = obs.get("planets", []) if isinstance(obs, dict) else obs.planets
    step = int(obs.get("step", 0) if isinstance(obs, dict) else getattr(obs, "step", 0))
    template = template_for(cluster_id)

    if step < template.first_launch:
        return []

    # Pro-rated target: by step s we should have launched
    # ceil(template.launches_30 * (s+1) / 30) fleets.
    target_so_far = int(math.ceil(template.launches_30 * (step + 1) / 30))
    if launches_so_far >= target_so_far:
        return []

    # Pick the best source: any of our planets with >5 ships
    # (idle-garrison threshold; below this we can't afford to launch).
    my_planets = [p for p in planets if p[1] == my_seat and p[5] > 5]
    if not my_planets:
        return []

    # Target selection — ROI-style (value / cost). The cluster TEMPLATE
    # controls *cadence* (how often we launch); target selection itself
    # is the standard production-per-(distance + ship-cost) ROI lookup
    # from `agents/simple/roi.py`. Penalising closer-than-template
    # targets — as a literal "match template.target_dist" formulation
    # would — is actively wrong: top-10's template-distance is what
    # they fire AT given the targets available, not what they prefer.
    candidates = []
    for src in my_planets:
        for t in planets:
            if t[1] == my_seat:
                continue
            d = math.hypot(t[2] - src[2], t[3] - src[3])
            cost = max(1, int(t[5]) + 1)
            # Skip self-owned fortresses we can't capture.
            if cost >= int(src[5]) - 5:
                continue
            # Standard ROI: production-per-(cost + distance), with a
            # mild bonus for matching template production rank so we
            # break ties toward high-prod targets when the cluster
            # template prefers them (e.g. cluster 0/3 ~ prod 3.3-3.5).
            roi = t[6] / (cost + d + 1.0)
            template_match = 1.0 - min(1.0, abs(t[6] - template.target_prod) / 3.0)
            score = roi * (1.0 + 0.2 * template_match)
            candidates.append((-score, d, src, t, cost))  # sort: max-score, then min-distance
    if not candidates:
        return []
    candidates.sort(key=lambda c: (c[0], c[1]))
    _, d, src, target, cost = candidates[0]
    aim = math.atan2(target[3] - src[3], target[2] - src[2])
    return [[int(src[0]), float(aim), int(cost)]]


__all__ = [
    "OVERLAY_HORIZON",
    "Template",
    "classify_board",
    "template_for",
    "propose_opening_actions",
]
