"""Learned value head — pure-NumPy forward pass, weights embedded inline.

The MLP weights (40 -> 128 -> 128 -> 1) live as a base64-encoded
NumPy `.npz` blob in this module so the bundler's plain-source inliner
(see `scripts/bundle_agent.py`) ships them straight into the submission
.py without needing PyTorch on the agent side.

Public surface mirrors `agents/baseline/value.py::favor`:

  favor_learned(obs, me, num_seats=2, gamma=DEFAULT_GAMMA) -> float

so the existing `select_favor_fn` dispatcher can wire it via
`BASELINE_VALUE_HEAD=learned`.

Inference budget: target median < 200 µs per call (the chooser invokes
the leaf eval ~N_candidates * K_horizon times per turn — see
`agents/baseline/chooser.py`). Hot path uses only `np.dot`, `np.maximum`,
and a single-row `(40,)` vector — no allocations beyond the small
intermediates.

Weight provenance: trained by `scripts/kaggle_value_head_kernel/train.py`
on the dataset at `data/value_head/`. After training, re-embed via
`scripts/embed_value_head_weights.py` (regenerates the WEIGHTS_B64
literal in this file).
"""

from __future__ import annotations

import base64
import io
import os
from typing import Any

import numpy as np

from lib.value_features import extract_features

DEFAULT_GAMMA = 0.99  # mirrors agents.baseline.value.DEFAULT_GAMMA

# ---------------------------------------------------------------------------
# Embedded weights
# ---------------------------------------------------------------------------
#
# The base64 string below is regenerated by
# `scripts/embed_value_head_weights.py`. While unset (initial state) the
# inference path falls back to a zero-weights identity that returns 0.0
# for every observation — this is intentional: it lets the bundler smoke
# work end-to-end before the first training run completes.

WEIGHTS_B64 = ""


def _load_weights() -> dict[str, np.ndarray] | None:
    """Decode the embedded base64 .npz blob into a weight dict.

    Returns None when WEIGHTS_B64 is empty (pre-training stub). Caller
    must handle the None case — `_get_weights()` does so by lazily
    falling back to the zero-net.
    """
    if not WEIGHTS_B64:
        return None
    blob = base64.b64decode(WEIGHTS_B64)
    with np.load(io.BytesIO(blob)) as d:
        return {
            "W0": d["W0"].astype(np.float32),
            "b0": d["b0"].astype(np.float32),
            "W1": d["W1"].astype(np.float32),
            "b1": d["b1"].astype(np.float32),
            "W2": d["W2"].astype(np.float32),
            "b2": d["b2"].astype(np.float32),
        }


def _zero_weights() -> dict[str, np.ndarray]:
    """Identity-ish fallback when no weights have been embedded yet.

    Returns weights producing constant-0 output. Used so the bundler
    smoke (Rule 46) can run before the first training pass completes.
    """
    return {
        "W0": np.zeros((40, 128), dtype=np.float32),
        "b0": np.zeros(128, dtype=np.float32),
        "W1": np.zeros((128, 128), dtype=np.float32),
        "b1": np.zeros(128, dtype=np.float32),
        "W2": np.zeros((128, 1), dtype=np.float32),
        "b2": np.zeros(1, dtype=np.float32),
    }


_W: dict[str, np.ndarray] | None = None


def _get_weights() -> dict[str, np.ndarray]:
    global _W
    if _W is None:
        _W = _load_weights() or _zero_weights()
    return _W


# ---------------------------------------------------------------------------
# Forward pass
# ---------------------------------------------------------------------------


def _forward(features: np.ndarray) -> float:
    """Pure-NumPy MLP forward: 40 -> 128 -> 128 -> 1.

    `features` must be shape `(40,)` float32. Returns a Python float so
    the caller can use it interchangeably with the hand-coded `favor()`.
    """
    w = _get_weights()
    h0 = np.maximum(0.0, features @ w["W0"] + w["b0"])
    h1 = np.maximum(0.0, h0 @ w["W1"] + w["b1"])
    out = h1 @ w["W2"] + w["b2"]
    return float(out[0])


def forward_batch(features: np.ndarray) -> np.ndarray:
    """Batched forward for offline benches / training-time eval. Not
    used on the agent hot path. `features` shape `(N, 40)` float32 ->
    `(N,)` float32.
    """
    w = _get_weights()
    h0 = np.maximum(0.0, features @ w["W0"] + w["b0"])
    h1 = np.maximum(0.0, h0 @ w["W1"] + w["b1"])
    return (h1 @ w["W2"] + w["b2"])[:, 0]


# ---------------------------------------------------------------------------
# Public surface — matches agents.baseline.value.favor
# ---------------------------------------------------------------------------


def favor_learned(
    obs: Any, me: int, num_seats: int = 2,
    gamma: float = DEFAULT_GAMMA,
) -> float:
    """Drop-in replacement for `agents.baseline.value.favor`.

    `gamma` is intentionally unused — the network learned its own time-
    discount via the `pv_horizon` feature in the global block. Argument
    kept for signature compat with the dispatcher.
    """
    feats = extract_features(obs, me=me, num_seats=num_seats)
    return _forward(feats)


# ---------------------------------------------------------------------------
# Diagnostic
# ---------------------------------------------------------------------------


def weights_loaded() -> bool:
    """True iff the embedded base64 blob is populated (post-training)."""
    return bool(WEIGHTS_B64)


def weights_summary() -> str:
    """One-liner for the agent-startup log."""
    w = _get_weights()
    n_params = sum(int(np.prod(a.shape)) for a in w.values())
    state = "trained" if weights_loaded() else "ZERO_FALLBACK"
    return (
        f"value_learned: {state}, {n_params} params, "
        f"BASELINE_VALUE_HEAD={os.environ.get('BASELINE_VALUE_HEAD', '')!r}"
    )
