"""baseline + pv_eta + distilled-ladder opp (Tier 2 v2) + B.3 value head.

Phase 6c composite: layers BOTH the distilled-ladder opp model (Tier 2 v2)
AND the B.3 CRN-paired-advantage value head on top of the pv_eta foundation.

The hypothesis behind this composite (from the plan):

> "B.3's value head was held at PI's call because its 18/32 = 56.2% lift
> vs launch_rules looked marginal. The mechanistic suspicion: B.3 reads
> a leaf state generated by pv_eta's STATIC opp model (lite_greedy
> via lookahead) — a leaf state that doesn't reflect what a real opp
> would do. If the opp model becomes realistic (Tier 2 distilled),
> B.3's labels become accurate and its lift should re-open."

Env vars set:
- `BASELINE_OPP_TIER=2`: distilled-ladder opp predictor in the chooser
  rollout (lib.opp_model.trained_logreg_policy v2, replaced 2026-05-31).
- `BASELINE_VH_LAMBDA=1.0`: B.3 head additive term ON at natural scale.
- `BASELINE_PV_ETA=1`: foundation lock.
- Standard peak-orbitfix preamble.

Bundler patches BOTH `_OPP_BOOSTER_B64` (in inlined lib/opp_model.py)
AND `_VH_MODEL_B64` (in inlined agents/baseline/_value_head.py).

At BASELINE_VH_LAMBDA=0, byte-equivalent to baseline_pv_eta_vh_dist.
At BASELINE_OPP_TIER=0, byte-equivalent to baseline_pv_eta_vh.
"""

from __future__ import annotations

import os as _os

# peak orbitfix preamble
_os.environ.setdefault("BASELINE_JOINT_AGGR", "1")
_os.environ.setdefault("BASELINE_JOINT_TOP_K", "5")
_os.environ.setdefault("BASELINE_JOINT_MAX_PAIRS", "60")
_os.environ.setdefault("BASELINE_REINFORCE_EMIT", "1")
_os.environ.setdefault("BASELINE_REINFORCE_ANTICIPATE", "1")
_os.environ.setdefault("BASELINE_NEUTRAL_BONUS", "2.0")
_os.environ.setdefault("BASELINE_NEUTRAL_EARLY_EXTRA", "1.5")
_os.environ.setdefault("BASELINE_NEUTRAL_EARLY_HORIZON", "50")
_os.environ.setdefault("BASELINE_ORBITAL_SAFETY", "1")

# Foundation: pv_eta time-discount.
_os.environ.setdefault("BASELINE_PV_ETA", "1")

# Composite layer 1: distilled-ladder opp model (Tier 2 v2).
_os.environ.setdefault("BASELINE_OPP_TIER", "2")
# See agents/baseline_pv_eta_vh_dist/main.py for the 0.15 rationale.
_os.environ.setdefault("BASELINE_OPP_FILTER_THRESHOLD", "0.15")

# Composite layer 2: B.3 CRN-advantage value head.
_os.environ.setdefault("BASELINE_VH_LAMBDA", "1.0")

# Kinematic-table bug fix (May-30; non-negotiable). Explicit set
# overrides any opponent-side setdefault in shared-process A/Bs.
_os.environ["KINEMATIC_TABLE_ENABLED"] = "0"

from agents.baseline.main import agent  # noqa: E402,F401
