"""Flatten agents/oracle/ into a single-file Kaggle submission.

Order: engine, features, policy_features, value, policy, planner — with all
intra-package imports stripped (every name is module-global after
concatenation) — plus the generated weight modules wrapped in function
scopes (their MU/SIGMA/LAYERS names collide between the two) and exposed as
_VALUE_WEIGHTS / _POLICY_WEIGHTS, which value.py / policy.py pick up from
globals() when the relative import fails. A minimal agent() entry replaces
main.py (no path discovery needed in a single file).

Usage:
  python scripts/build_oracle_bundle.py [--out submissions/oracle_v1.py]

Always follow with the parity + smoke gates (see state/ORACLE_STRATEGY.md).
"""
from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PKG = REPO / "agents" / "oracle"

MODULES = ["engine.py", "features.py", "policy_features.py",
           "value.py", "policy.py", "planner.py"]
WEIGHTS = [("value_weights.py", "_VALUE_WEIGHTS",
            ["MU", "SIGMA", "LAYERS", "HEAD_WIN", "HEAD_SHARE"]),
           ("policy_weights.py", "_POLICY_WEIGHTS",
            ["MU", "SIGMA", "LAYERS", "HEAD_FIRE", "HEAD_FRAC"])]

FOOTER = '''

# --------------------------------------------------------------- entry point
_PLANNER = Planner()


def agent(obs, configuration=None):
    try:
        return _PLANNER.act(obs)
    except Exception:
        import traceback as _tb
        import sys as _sys
        _tb.print_exc(file=_sys.stderr)
        return []
'''


def strip_pkg_imports(src: str) -> str:
    """Remove TOP-LEVEL `from .x import ...` statements (incl.
    parenthesized). Indented ones (inside try/except fallbacks) stay: they
    raise at runtime in the flat bundle and the except path takes over."""
    out = []
    skipping = False
    depth = 0
    for line in src.splitlines():
        if not skipping:
            ls = line
            if ls.startswith("from .") or ls.startswith("from . "):
                depth = line.count("(") - line.count(")")
                if depth > 0:
                    skipping = True
                continue
            out.append(line)
        else:
            depth += line.count("(") - line.count(")")
            if depth <= 0:
                skipping = False
    return "\n".join(out)


def wrap_weights(fname: str, global_name: str, exports: list) -> str:
    src = (PKG / fname).read_text()
    body = "\n".join("    " + ln if ln.strip() else ln
                     for ln in src.splitlines())
    ret = ", ".join(f"{e}={e}" for e in exports)
    return (f"def _load{global_name}():\n{body}\n"
            f"    from types import SimpleNamespace\n"
            f"    return SimpleNamespace({ret})\n\n"
            f"{global_name} = _load{global_name}()\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "submissions" / "oracle_v1.py"))
    args = ap.parse_args()

    parts = ['"""Oracle agent — single-file bundle. '
             'Generated by scripts/build_oracle_bundle.py."""']
    for fname, gname, exports in WEIGHTS:
        if (PKG / fname).exists():
            parts.append(wrap_weights(fname, gname, exports))
        else:
            print(f"WARNING: {fname} missing — bundle will use fallbacks")
    for m in MODULES:
        src = (PKG / m).read_text()
        parts.append(f"\n# {'=' * 66}\n# {m}\n# {'=' * 66}\n"
                     + strip_pkg_imports(src))
    parts.append(FOOTER)
    out = Path(args.out)
    out.write_text("\n".join(parts))
    # syntax gate
    import ast
    ast.parse(out.read_text())
    print(f"wrote {out} ({out.stat().st_size // 1024} KB), syntax OK")


if __name__ == "__main__":
    main()
