#!/usr/bin/env bash
# Build a single-file precision_v3.py by concatenating all agents/precision/
# modules in dependency order. Strips package-relative imports; defines a
# top-level agent(obs) function. Matches the convention of successful
# competitor submissions (v2.py, v3_snipe.py).
#
# Output: submissions/precision_v3.py

set -euo pipefail

REPO="$(cd "$(dirname "$0")"/.. && pwd)"
SRC="$REPO/agents/precision"
OUT="$REPO/submissions/precision_v3.py"
mkdir -p "$(dirname "$OUT")"

# Dependency order: sim → prediction → fast_sim → intercept → scoring →
# enemy_model → bundling → planner. main.py is replaced wholesale.
MODULES=(sim prediction fast_sim intercept scoring enemy_model bundling planner)

cat > "$OUT" <<'EOF'
"""precision_v3 — single-file Kaggle submission bundle.

Auto-generated by scripts/pack_precision_single.sh from agents/precision/.
Modules concatenated in dependency order; relative imports stripped; the
top-level `agent(obs)` is defined at the bottom.
"""
from __future__ import annotations

import dataclasses
import math
import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Iterable

EOF

python3 - "$SRC" "$OUT" <<'PY' "${MODULES[@]}"
import os, re, sys
src_dir = sys.argv[1]
out_path = sys.argv[2]
modules = sys.argv[3:]

# Drop these lines/patterns from each module's content.
SKIP_PREFIXES = (
    "from __future__",
    "import os",
    "import sys",
    "import time",
    "import math",
    "import dataclasses",
    "from collections",
    "from dataclasses",
    "from typing",
    "from agents.precision",
    "from agents.precision.prediction",
)
STRIP_LINES_RE = re.compile(
    r"^(from agents\.precision[^\n]*|import time|import math|import dataclasses|"
    r"from __future__ [^\n]*|import os|import sys|"
    r"from collections [^\n]*|from dataclasses [^\n]*|from typing [^\n]*)$",
    re.MULTILINE,
)

out = open(out_path, "a")
for mod in modules:
    path = os.path.join(src_dir, f"{mod}.py")
    with open(path) as f:
        body = f.read()
    body = STRIP_LINES_RE.sub("", body)
    # Flatten module-qualified refs to bare names (single-file namespace).
    # All sibling modules' top-level symbols share one namespace post-merge.
    QUALIFIED_REFS = [
        ("prediction.", ""), ("sim.", ""), ("intercept.", ""),
        ("fast_sim.", ""), ("scoring.", ""), ("enemy_model.", ""),
        ("bundling.", ""),
    ]
    # Don't strip `sim.EPISODE_STEPS` if `sim` is a parameter name — risky,
    # so we only strip when followed by an UPPER or lower-snake_case identifier
    # that we know is one of our exports. Simplest safe transform: just strip
    # the prefix on tokens that follow `<modname>.<identifier>` where identifier
    # starts with a-z or A-Z.
    for prefix, _ in QUALIFIED_REFS:
        # Replace only when preceded by a non-identifier char (whitespace, [, (, ,, etc.)
        body = re.sub(
            r"(?<![A-Za-z0-9_])" + re.escape(prefix) + r"(?=[A-Za-z_])",
            "",
            body,
        )
    # Drop redundant blank-line clusters left by the strip.
    body = re.sub(r"\n{3,}", "\n\n", body)
    out.write(f"\n# ===== {mod}.py =====\n")
    out.write(body.rstrip() + "\n")
out.close()
PY

# Append the agent entry point.
cat >> "$OUT" <<'EOF'


# ===== agent entry point =====

def agent(obs):
    """Return a list of [src_id, angle, ships] launches."""
    t0 = time.perf_counter()
    try:
        world = parse_world(obs)
    except Exception:
        return []
    if world["step"] == 0:
        return []
    deadline = t0 + 0.85
    try:
        chosen = plan_turn(world, deadline=deadline)
    except Exception:
        chosen = []
    return emit_actions(chosen)
EOF

# Quick byte-count + syntax check.
LINES=$(wc -l < "$OUT")
SIZE=$(stat -c %s "$OUT")
echo "Built: $OUT ($LINES lines, $SIZE bytes)"
python3 -m py_compile "$OUT" && echo "Syntax OK"
