"""Autonomous v7 ablation sweep.

For each variant in {v7_0_drop_one, v7_1_target_swap, v7_2_ship_sweep,
v7_3_archetype, v7_4_hungarian, v7_combined}:

  1. Run a 2P A/B vs `submissions/v3.5.1.py` over N seeds × both sides.
  2. Compute Wilson 95% lower bound on the variant's winrate.
  3. Verdict: PASS if Wilson lo ≥ 0.55, NEUTRAL if ≥ 0.45, FAIL otherwise.

Writes a markdown summary table to `audit/2026-05-12-v7-iteration.md`
and a JSON artifact per variant to `audit/tournaments/v7-*.json`.

Skips bundling — bundles are produced only on PI sign-off. The source
agents under `agents/v7_ablations/*/main.py` are loaded directly by
the tournament harness via `importlib.util.spec_from_file_location`.

CLI:
    python scripts/run_v7_ablation.py [--seeds 16] [--workers 4]
                                       [--variants v7_0,v7_1,...]

Per Rule 31 the loop is sequential (one tournament at a time);
internal parallelism uses `workers` for game-level concurrency.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from scripts.tournament import run_tournament  # noqa: E402
from scripts.run_iter2_ablation import wilson_lower  # noqa: E402


OUT_DIR = REPO / "audit" / "tournaments"
SUMMARY_PATH = REPO / "audit" / "2026-05-12-v7-iteration.md"

ALL_VARIANTS = [
    "v7_0_drop_one",
    "v7_1_target_swap",
    "v7_2_ship_sweep",
    "v7_3_archetype",
    "v7_4_hungarian",
    "v7_combined",
]


def _agent_path(name: str) -> Path:
    if name == "v7_combined":
        return REPO / "agents" / "v7_combined" / "main.py"
    return REPO / "agents" / "v7_ablations" / name / "main.py"


def _verdict(wilson_lo: float) -> str:
    if wilson_lo >= 0.55:
        return "PASS"
    if wilson_lo >= 0.45:
        return "NEUTRAL"
    return "FAIL"


def _ab_one_variant(
    variant: str,
    seeds: int,
    workers: int,
    baseline_label: str,
    baseline_path: Path,
) -> dict:
    """Run a single 2P A/B between `variant` and the baseline.

    Each seed runs twice (variant=P0 / baseline=P0) so we cover both
    starting positions. Returns a summary dict.
    """
    agents = {
        variant: str(_agent_path(variant)),
        baseline_label: str(baseline_path),
    }
    seed_list = list(range(seeds))

    t0 = time.perf_counter()
    result = run_tournament(
        agents=agents,
        seeds=seed_list,
        include_self_play=False,
        workers=workers,
        progress=False,
        out_dir=OUT_DIR,
    )
    elapsed_s = time.perf_counter() - t0

    p0_stat = result.matrix[variant][baseline_label]
    p1_stat = result.matrix[baseline_label][variant]
    v_wins = p0_stat.p0_wins + p1_stat.p1_wins
    v_losses = p0_stat.p1_wins + p1_stat.p0_wins
    v_draws = p0_stat.draws + p1_stat.draws
    n = v_wins + v_losses + v_draws
    wr = v_wins / n if n else 0.0
    wilson_lo = wilson_lower(v_wins, n)
    verdict = _verdict(wilson_lo)

    # p95 turn ms across both seats (variant only)
    variant_p95_ms = max(p0_stat.p0_p95_turn_ms, p1_stat.p1_p95_turn_ms)

    return {
        "variant": variant,
        "wins": v_wins,
        "losses": v_losses,
        "draws": v_draws,
        "n": n,
        "winrate": wr,
        "wilson_lo": wilson_lo,
        "verdict": verdict,
        "variant_p95_turn_ms": variant_p95_ms,
        "elapsed_s": elapsed_s,
        "json_artifact": (OUT_DIR / f"{result.timestamp_utc.replace(':','').replace('-','')}.json").name,
    }


def _write_summary(rows: list[dict], seeds: int):
    """Markdown audit doc."""
    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    today = datetime.utcnow().strftime("%Y-%m-%d")
    lines.append(f"# v7 minimax — ablation sweep results ({today})\n\n")
    lines.append(
        f"> Auto-generated by `scripts/run_v7_ablation.py`.\n"
        f"> Branch: `claude/game-ai-lookahead-3ucqH`.\n"
        f"> Baseline: `submissions/v3.5.1.py` (live submission #52565976, PENDING).\n"
        f"> Per-variant: {seeds} seeds × 2 sides = {seeds*2} games. "
        f"Wilson 95% lower bound; PASS ≥ 0.55, NEUTRAL ≥ 0.45, FAIL otherwise.\n\n"
    )
    lines.append("## 2P A/B vs v3.5.1\n\n")
    lines.append(
        "| Variant | W/L/D | wins/n | winrate | Wilson lo | p95 ms | verdict |\n"
        "|---|---|---|---:|---:|---:|---|\n"
    )
    for r in rows:
        lines.append(
            f"| `{r['variant']}` | "
            f"{r['wins']}/{r['losses']}/{r['draws']} | "
            f"{r['wins']}/{r['n']} | "
            f"{r['winrate']*100:.1f}% | "
            f"{r['wilson_lo']*100:.1f}% | "
            f"{r['variant_p95_turn_ms']:.0f} | "
            f"**{r['verdict']}** |\n"
        )
    lines.append("\n")

    # Aggregate verdict
    passers = [r for r in rows if r["verdict"] == "PASS"]
    neutrals = [r for r in rows if r["verdict"] == "NEUTRAL"]
    fails = [r for r in rows if r["verdict"] == "FAIL"]
    lines.append("## Summary\n\n")
    lines.append(f"- **PASS:** {[r['variant'] for r in passers] or 'none'}\n")
    lines.append(f"- **NEUTRAL:** {[r['variant'] for r in neutrals] or 'none'}\n")
    lines.append(f"- **FAIL:** {[r['variant'] for r in fails] or 'none'}\n\n")

    lines.append("## Decision tree\n\n")
    if passers:
        best = max(passers, key=lambda r: r["wilson_lo"])
        lines.append(
            f"- **Recommended submission candidate:** `{best['variant']}` "
            f"(Wilson lo {best['wilson_lo']*100:.1f}%).\n"
            f"  - Bundle next via `python -m scripts.bundle_agent "
            f"agents/{'v7_combined' if best['variant'] == 'v7_combined' else 'v7_ablations/' + best['variant']} "
            f"--lib-modules ... --extra fast_sim opp_model v7_search`.\n"
            f"  - Then 16-seed 4P FFA panel before PI submission decision.\n"
        )
    elif neutrals:
        lines.append(
            f"- **No PASS.** {len(neutrals)} variants NEUTRAL — closer to "
            f"baseline than to lift. Likely K=10 is too short; investigate "
            f"K=20 next session and/or richer enumerators.\n"
        )
    else:
        lines.append(
            f"- **All variants FAIL.** Strong evidence the 1-ply forward-"
            f"eval framework needs a different shape. Hypotheses to test "
            f"next session: (a) depth-2 minimax with width-3 beam; (b) "
            f"asymmetric opp model (Tier 0 vs Tier 1 mix); (c) replace "
            f"`ship_totals` scoring head with `planets_lost_prevented + "
            f"planets_captured`.\n"
        )

    SUMMARY_PATH.write_text("".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seeds", type=int, default=16,
                        help="seeds per variant (each runs both sides)")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument(
        "--variants", default=",".join(ALL_VARIANTS),
        help="comma-separated variant names to run",
    )
    parser.add_argument(
        "--baseline", default="submissions/v3.5.1.py",
        help="baseline agent path (relative to repo root)",
    )
    args = parser.parse_args()

    baseline_path = REPO / args.baseline
    if not baseline_path.exists():
        sys.exit(f"baseline not found: {baseline_path}")

    variants = [v.strip() for v in args.variants.split(",") if v.strip()]
    print(
        f"v7 ablation sweep: {len(variants)} variants × {args.seeds} seeds × 2 sides\n"
        f"  baseline = {args.baseline}\n"
        f"  workers  = {args.workers}\n"
    )

    rows: list[dict] = []
    overall_t0 = time.perf_counter()
    for i, variant in enumerate(variants, 1):
        path = _agent_path(variant)
        if not path.exists():
            print(f"[{i}/{len(variants)}] {variant}: MISSING ({path}); skipping")
            continue
        print(f"[{i}/{len(variants)}] {variant}: running A/B...", flush=True)
        row = _ab_one_variant(
            variant, args.seeds, args.workers,
            baseline_label="v3.5.1",
            baseline_path=baseline_path,
        )
        rows.append(row)
        print(
            f"    {row['wins']}/{row['n']} = {row['winrate']*100:.1f}% | "
            f"Wilson lo {row['wilson_lo']*100:.1f}% | "
            f"p95 {row['variant_p95_turn_ms']:.0f} ms | "
            f"{row['verdict']} | "
            f"{row['elapsed_s']:.0f}s",
            flush=True,
        )

    total_s = time.perf_counter() - overall_t0
    print(f"\nSweep done in {total_s:.0f}s ({total_s/60:.1f} min).")

    _write_summary(rows, seeds=args.seeds)
    print(f"Summary: {SUMMARY_PATH.relative_to(REPO)}")

    # Also dump a JSON for downstream tooling.
    json_path = REPO / "audit" / f"2026-05-12-v7-iteration-summary.json"
    json_path.write_text(json.dumps(rows, indent=2))
    print(f"JSON:    {json_path.relative_to(REPO)}")

    # Exit code: nonzero if no PASS
    any_pass = any(r["verdict"] == "PASS" for r in rows)
    return 0 if any_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
